-- MySQL Script generated by MySQL Workbench
-- jue 05 mar 2015 07:34:14 COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tpe_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tpe_db` ;

-- -----------------------------------------------------
-- Schema tpe_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tpe_db` DEFAULT CHARACTER SET utf8 ;
USE `tpe_db` ;

-- -----------------------------------------------------
-- Table `tpe_db`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpe_db`.`category` ;

CREATE TABLE IF NOT EXISTS `tpe_db`.`category` (
  `category_id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NULL DEFAULT NULL,
  `category_description` VARCHAR(255) NULL DEFAULT NULL,
  `entity_class` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpe_db`.`region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpe_db`.`region` ;

CREATE TABLE IF NOT EXISTS `tpe_db`.`region` (
  `region_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `region_name` VARCHAR(100) NULL DEFAULT NULL,
  `region_parent` BIGINT(20) NULL DEFAULT NULL,
  `region_alpha_iso` VARCHAR(10) NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `altitude` DOUBLE NULL DEFAULT NULL,
  `category_id` INT(11) NULL DEFAULT NULL,
  `region_level` VARCHAR(45) NULL DEFAULT NULL,
  `region_numeric_iso` SMALLINT(6) NULL DEFAULT NULL,
  `zoom` SMALLINT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`region_id`),
  UNIQUE INDEX `region_alpha_iso_UNIQUE` (`region_alpha_iso` ASC),
  UNIQUE INDEX `region_numeric_iso_UNIQUE` (`region_numeric_iso` ASC),
  INDEX `fk_region_region_idx` (`region_parent` ASC),
  INDEX `fk_region_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_region_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `tpe_db`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_region_region`
    FOREIGN KEY (`region_parent`)
    REFERENCES `tpe_db`.`region` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 107
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpe_db`.`station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpe_db`.`station` ;

CREATE TABLE IF NOT EXISTS `tpe_db`.`station` (
  `station_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `station_name` VARCHAR(100) NULL DEFAULT NULL,
  `station_longitude` DOUBLE NULL DEFAULT NULL,
  `station_latitude` DOUBLE NULL DEFAULT NULL,
  `region_id` BIGINT(20) NULL DEFAULT NULL,
  `station_altitude` DOUBLE NULL DEFAULT NULL,
  `station_number` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`station_id`),
  INDEX `fk_station_region_idx` USING BTREE (`region_id` ASC),
  CONSTRAINT `fk_station_region`
    FOREIGN KEY (`region_id`)
    REFERENCES `tpe_db`.`region` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 818
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpe_db`.`climate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpe_db`.`climate` ;

CREATE TABLE IF NOT EXISTS `tpe_db`.`climate` (
  `climate_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `station_id` BIGINT(20) NULL DEFAULT NULL,
  `category_id` INT(11) NULL DEFAULT NULL,
  `author` VARCHAR(255) NULL DEFAULT NULL,
  `source` VARCHAR(255) NULL DEFAULT NULL,
  `year` VARCHAR(10) NULL DEFAULT NULL,
  `precipitation` DOUBLE NULL DEFAULT NULL,
  `min_temperature` DOUBLE NULL DEFAULT NULL,
  `max_temperature` DOUBLE NULL DEFAULT NULL,
  `radiation` DOUBLE NULL DEFAULT NULL,
  `month` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`climate_id`),
  INDEX `fk_climate_station_idx` (`station_id` ASC),
  INDEX `fk_climate_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_climate_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `tpe_db`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_climate_station`
    FOREIGN KEY (`station_id`)
    REFERENCES `tpe_db`.`station` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2068
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpe_db`.`crop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpe_db`.`crop` ;

CREATE TABLE IF NOT EXISTS `tpe_db`.`crop` (
  `crop_id` INT(11) NOT NULL AUTO_INCREMENT,
  `crop_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`crop_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpe_db`.`cultivar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpe_db`.`cultivar` ;

CREATE TABLE IF NOT EXISTS `tpe_db`.`cultivar` (
  `cultivar_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cultivar_name` VARCHAR(100) NULL DEFAULT NULL,
  `crop_id` INT(11) NULL DEFAULT NULL,
  `vegetative_start` INT(11) NULL DEFAULT NULL,
  `vegetative_end` INT(11) NULL DEFAULT NULL,
  `fillinggrain_hfe_start` INT(11) NULL DEFAULT NULL,
  `reproductive_hfe_end` INT(11) NULL DEFAULT NULL,
  `fillinggrain_lfe_start` INT(11) NULL DEFAULT NULL,
  `reproductive_lfe_end` INT(11) NULL DEFAULT NULL,
  `fillinggrain_fe_start` INT(11) NULL DEFAULT NULL,
  `reproductive_fe_end` INT(11) NULL DEFAULT NULL,
  `reproductive_start` INT(11) NULL DEFAULT NULL,
  `fillinggrain_end` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cultivar_id`),
  INDEX `fk_variety_crop_idx` (`crop_id` ASC),
  CONSTRAINT `fk_variety_crop`
    FOREIGN KEY (`crop_id`)
    REFERENCES `tpe_db`.`crop` (`crop_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpe_db`.`environment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpe_db`.`environment` ;

CREATE TABLE IF NOT EXISTS `tpe_db`.`environment` (
  `environment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `environment_name` VARCHAR(100) NOT NULL,
  `environment_code` VARCHAR(45) NULL DEFAULT NULL,
  `environment_color` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`environment_id`, `environment_name`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpe_db`.`soil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpe_db`.`soil` ;

CREATE TABLE IF NOT EXISTS `tpe_db`.`soil` (
  `soil_id` INT(11) NOT NULL AUTO_INCREMENT,
  `soil_name` VARCHAR(45) NULL DEFAULT NULL,
  `soil_code` VARCHAR(45) NULL DEFAULT NULL,
  `soil_color` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`soil_id`),
  UNIQUE INDEX `idx_soil_pk` (`soil_id` ASC),
  UNIQUE INDEX `soil_code_UNIQUE` (`soil_code` ASC),
  INDEX `idx_soil_lookup` (`soil_code` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpe_db`.`environment_soil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpe_db`.`environment_soil` ;

CREATE TABLE IF NOT EXISTS `tpe_db`.`environment_soil` (
  `env_soil_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sowing_date` VARCHAR(50) NULL DEFAULT NULL,
  `prob_occurance` FLOAT NULL DEFAULT NULL,
  `environment_id` INT(11) NULL DEFAULT NULL,
  `soil_id` INT(11) NULL DEFAULT NULL,
  `region_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`env_soil_id`),
  INDEX `fk_env_soil_idx` (`soil_id` ASC),
  INDEX `fk_env_env_idx` (`environment_id` ASC),
  INDEX `fk_env_region_idx` (`region_id` ASC),
  CONSTRAINT `fk_env_soil_env`
    FOREIGN KEY (`environment_id`)
    REFERENCES `tpe_db`.`environment` (`environment_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_env_soil_region`
    FOREIGN KEY (`region_id`)
    REFERENCES `tpe_db`.`region` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_env_soil_soil`
    FOREIGN KEY (`soil_id`)
    REFERENCES `tpe_db`.`soil` (`soil_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 169
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpe_db`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpe_db`.`tag` ;

CREATE TABLE IF NOT EXISTS `tpe_db`.`tag` (
  `tag_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tag_name` VARCHAR(100) NOT NULL,
  `tag_url` VARCHAR(255) NULL DEFAULT NULL,
  `tag_clicks` INT(11) NULL DEFAULT NULL,
  `created_on` TIMESTAMP NULL DEFAULT NULL,
  `tag_weight` INT(11) NULL DEFAULT NULL,
  `enabled` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpe_db`.`link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpe_db`.`link` ;

CREATE TABLE IF NOT EXISTS `tpe_db`.`link` (
  `link_id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `clicks` INT(11) NULL DEFAULT NULL,
  `created_on` DATETIME NULL DEFAULT NULL,
  `tag_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`link_id`),
  INDEX `fk_link_tag_idx` (`tag_id` ASC),
  CONSTRAINT `fk_link_tag`
    FOREIGN KEY (`tag_id`)
    REFERENCES `tpe_db`.`tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpe_db`.`model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpe_db`.`model` ;

CREATE TABLE IF NOT EXISTS `tpe_db`.`model` (
  `model_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `model_description` TEXT NULL DEFAULT NULL,
  `model_date` TIMESTAMP NULL DEFAULT NULL,
  `cultivar_id` BIGINT(20) NULL DEFAULT NULL,
  `number` INT(11) NULL DEFAULT NULL,
  `model_title` VARCHAR(255) NULL DEFAULT NULL,
  `simulation_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`model_id`),
  INDEX `fk_model_variety_idx` (`cultivar_id` ASC),
  CONSTRAINT `fk_model_cultivar`
    FOREIGN KEY (`cultivar_id`)
    REFERENCES `tpe_db`.`cultivar` (`cultivar_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpe_db`.`series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpe_db`.`series` ;

CREATE TABLE IF NOT EXISTS `tpe_db`.`series` (
  `series_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`series_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpe_db`.`phenology_growth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpe_db`.`phenology_growth` ;

CREATE TABLE IF NOT EXISTS `tpe_db`.`phenology_growth` (
  `result_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `result_date` TIMESTAMP NULL DEFAULT NULL,
  `cultivar_id` BIGINT(20) NULL DEFAULT NULL,
  `model_id` BIGINT(20) NULL DEFAULT NULL,
  `category_id` INT(11) NULL DEFAULT NULL,
  `region_id` BIGINT(20) NULL DEFAULT NULL,
  `station_id` BIGINT(20) NULL DEFAULT NULL,
  `Total_Days_Eme_Ipa` INT(11) NULL DEFAULT NULL,
  `Total_Days_Eme_Flo` INT(11) NULL DEFAULT NULL,
  `Total_Days_Eme_Mad` INT(11) NULL DEFAULT NULL,
  `Num_Days_Eme_Ipa` INT(11) NULL DEFAULT NULL,
  `Num_Days_IPa_Flo` INT(11) NULL DEFAULT NULL,
  `Num_Days_Flo_Mad` INT(11) NULL DEFAULT NULL,
  `Sum_Tmin_Eme_Ipa` FLOAT NULL DEFAULT NULL,
  `Sum_Tmin_IPa_Flo` FLOAT NULL DEFAULT NULL,
  `Sum_Tmin_Flo_Mad` FLOAT NULL DEFAULT NULL,
  `Max_Tmin_Eme_Ipa` FLOAT NULL DEFAULT NULL,
  `Max_Tmin_IPa_Flo` FLOAT NULL DEFAULT NULL,
  `Max_Tmin_Flo_Mad` FLOAT NULL DEFAULT NULL,
  `Sum_Tmax_Eme_Ipa` FLOAT NULL DEFAULT NULL,
  `Sum_Tmax_IPa_Flo` FLOAT NULL DEFAULT NULL,
  `Sum_Tmax_Flo_Mad` FLOAT NULL DEFAULT NULL,
  `Max_Tmax_Eme_Ipa` FLOAT NULL DEFAULT NULL,
  `Max_Tmax_IPa_Flo` FLOAT NULL DEFAULT NULL,
  `Max_Tmax_Flo_Mad` FLOAT NULL DEFAULT NULL,
  `Sum_RAIN_Eme_Ipa` FLOAT NULL DEFAULT NULL,
  `Sum_RAIN_IPa_Flo` FLOAT NULL DEFAULT NULL,
  `Sum_RAIN_Flo_Mad` FLOAT NULL DEFAULT NULL,
  `NFLV_Eme_Ipa` FLOAT NULL DEFAULT NULL,
  `NFLV_IPa_Flo` FLOAT NULL DEFAULT NULL,
  `NFLV_Flo_Mad` FLOAT NULL DEFAULT NULL,
  `Max_SLA_Eme_Ipa` FLOAT NULL DEFAULT NULL,
  `Max_SLA_IPa_Flo` FLOAT NULL DEFAULT NULL,
  `Max_SLA_Flo_Mad` FLOAT NULL DEFAULT NULL,
  `Max_NSP_Eme_Ipa` INT(11) NULL DEFAULT NULL,
  `Max_NSP_IPa_Flo` INT(11) NULL DEFAULT NULL,
  `Max_NSP_Flo_Mad` INT(11) NULL DEFAULT NULL,
  `Max_LAI_Eme_Ipa` FLOAT NULL DEFAULT NULL,
  `Max_LAI_IPa_Flo` FLOAT NULL DEFAULT NULL,
  `Max_LAI_Flo_Mad` FLOAT NULL DEFAULT NULL,
  `Max_WAGT_Eme_Ipa` FLOAT NULL DEFAULT NULL,
  `Max_WAGT_IPa_Flo` FLOAT NULL DEFAULT NULL,
  `Max_WAGT_Flo_Mad` FLOAT NULL DEFAULT NULL,
  `Max_WST_Eme_Ipa` FLOAT NULL DEFAULT NULL,
  `Max_WST_IPa_Flo` FLOAT NULL DEFAULT NULL,
  `Max_WST_Flo_Mad` FLOAT NULL DEFAULT NULL,
  `Max_WLVG_Eme_Ipa` FLOAT NULL DEFAULT NULL,
  `Max_WLVG_IPa_Flo` FLOAT NULL DEFAULT NULL,
  `Max_WLVG_Flo_Mad` FLOAT NULL DEFAULT NULL,
  `Max_WSO_Eme_Ipa` FLOAT NULL DEFAULT NULL,
  `Max_WSO_IPa_Flo` FLOAT NULL DEFAULT NULL,
  `Max_WSO_Flo_Mad` FLOAT NULL DEFAULT NULL,
  `Sum_TRW_Eme_Ipa` FLOAT NULL DEFAULT NULL,
  `Sum_TRW_IPa_Flo` FLOAT NULL DEFAULT NULL,
  `Sum_TRW_Flo_Mad` FLOAT NULL DEFAULT NULL,
  `ETDCUM` FLOAT NULL DEFAULT NULL,
  `EVSCCUM` FLOAT NULL DEFAULT NULL,
  `TRCCUM` FLOAT NULL DEFAULT NULL,
  `WRR14` FLOAT NULL DEFAULT NULL,
  `WSO` FLOAT NULL DEFAULT NULL,
  `WAGT` FLOAT NULL DEFAULT NULL,
  `PARCUM` FLOAT NULL DEFAULT NULL,
  `TS` FLOAT NULL DEFAULT NULL,
  `TMAXC` FLOAT NULL DEFAULT NULL,
  `TMINC` FLOAT NULL DEFAULT NULL,
  `TAVERC` FLOAT NULL DEFAULT NULL,
  `RAINCUM` FLOAT NULL DEFAULT NULL,
  `IRCUM` FLOAT NULL DEFAULT NULL,
  `RUNOFCUM` FLOAT NULL DEFAULT NULL,
  `TRWCUM` FLOAT NULL DEFAULT NULL,
  `EVSWCUM` FLOAT NULL DEFAULT NULL,
  `DRAICUM` FLOAT NULL DEFAULT NULL,
  `EMD` INT(11) NULL DEFAULT NULL,
  `DAE` INT(11) NULL DEFAULT NULL,
  `soil_id` INT(11) NULL DEFAULT NULL,
  `scenario` VARCHAR(50) NULL DEFAULT NULL,
  `window_id` INT(11) NULL DEFAULT NULL,
  `year` VARCHAR(10) NULL DEFAULT NULL,
  `cluster` SMALLINT(6) NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  `sowing_date` VARCHAR(50) NULL DEFAULT NULL,
  `environment_id` INT(11) NULL DEFAULT NULL,
  `lai` FLOAT NULL DEFAULT NULL,
  `actual_transpiration` FLOAT NULL DEFAULT NULL,
  `stress_index` FLOAT NULL DEFAULT NULL,
  `average_weekly_rain` FLOAT NULL DEFAULT NULL,
  `graphic_name` VARCHAR(60) NULL DEFAULT NULL,
  `cluster_code` VARCHAR(60) NULL DEFAULT NULL,
  `series_id` INT(11) NULL DEFAULT NULL,
  `value` DOUBLE NULL DEFAULT NULL,
  `pcew` FLOAT NULL DEFAULT NULL,
  `variable` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`result_id`),
  INDEX `fk_yield_variety_idx` (`cultivar_id` ASC),
  INDEX `fk_result_model_idx` (`model_id` ASC),
  INDEX `fk_result_category_idx` (`category_id` ASC),
  INDEX `fk_result_station_idx` (`station_id` ASC),
  INDEX `fk_result_region_idx` (`region_id` ASC),
  INDEX `fk_phenology_soil_idx` (`soil_id` ASC),
  INDEX `fk_result_env_idx` (`environment_id` ASC),
  INDEX `fk_phenology_growth_series` (`series_id` ASC),
  CONSTRAINT `fk_phenology_growth_series`
    FOREIGN KEY (`series_id`)
    REFERENCES `tpe_db`.`series` (`series_id`),
  CONSTRAINT `fk_phenology_soil`
    FOREIGN KEY (`soil_id`)
    REFERENCES `tpe_db`.`soil` (`soil_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_result_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `tpe_db`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_result_cultivar`
    FOREIGN KEY (`cultivar_id`)
    REFERENCES `tpe_db`.`cultivar` (`cultivar_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_result_env`
    FOREIGN KEY (`environment_id`)
    REFERENCES `tpe_db`.`environment` (`environment_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_result_model`
    FOREIGN KEY (`model_id`)
    REFERENCES `tpe_db`.`model` (`model_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_result_region`
    FOREIGN KEY (`region_id`)
    REFERENCES `tpe_db`.`region` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_result_station`
    FOREIGN KEY (`station_id`)
    REFERENCES `tpe_db`.`station` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 59950
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpe_db`.`soil_property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpe_db`.`soil_property` ;

CREATE TABLE IF NOT EXISTS `tpe_db`.`soil_property` (
  `property_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `soil_id` INT(11) NULL DEFAULT NULL,
  `station_id` BIGINT(20) NULL DEFAULT NULL,
  `model_id` BIGINT(20) NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `ph` FLOAT NULL DEFAULT NULL,
  `depth` FLOAT NULL DEFAULT NULL,
  `organic_matter` FLOAT NULL DEFAULT NULL,
  `bulky_density` FLOAT NULL DEFAULT NULL,
  `taxonomy` FLOAT NULL DEFAULT NULL,
  `organic_carbon` FLOAT NULL DEFAULT NULL,
  `available_soil_water` FLOAT NULL DEFAULT NULL,
  `cation_exchange` FLOAT NULL DEFAULT NULL,
  `water_capacity_wilt_point` FLOAT NULL DEFAULT NULL,
  `water_content_field_capacity` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`property_id`),
  INDEX `fk_property_soil_idx` (`soil_id` ASC),
  INDEX `fk_property_station_idx` (`station_id` ASC),
  INDEX `fk_property_model_idx` (`model_id` ASC),
  CONSTRAINT `fk_property_model`
    FOREIGN KEY (`model_id`)
    REFERENCES `tpe_db`.`model` (`model_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_property_soil`
    FOREIGN KEY (`soil_id`)
    REFERENCES `tpe_db`.`soil` (`soil_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_property_station`
    FOREIGN KEY (`station_id`)
    REFERENCES `tpe_db`.`station` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1280
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpe_db`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpe_db`.`type` ;

CREATE TABLE IF NOT EXISTS `tpe_db`.`type` (
  `type_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
